---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  labels:
    app: website
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
      version: v1
  template:
    metadata:
      labels:
        app: website
        version: v1
    spec:
      nodeSelector:
        size: big
      imagePullSecrets:
        - name: docker-registry-key
      containers:
        - name: website
          image: website
          resources:
            limits:
              cpu: "1.0"
              memory: 1024Mi
            requests:
              cpu: "0.1"
              memory: 512Mi
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
            initialDelaySeconds: 900
            timeoutSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: tellae
  labels:
    app: website
spec:
  type: ClusterIP
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
